#!/bin/bash
SELF_PATH="$(dirname "$(readlink -f $0)")"
CONFIGPATH=()
# put your app paths here 
#CONFIGPATH+=("/srv/containers/lb/srv/apps/*/.ndg")

generate_config(){
  extrajson=""; :>/tmp/.config 
  for dir in "${CONFIGPATH[@]}"; do find $dir/config >> /tmp/.config; done
  while read file; do source $file 
    [[ -n $HOST ]] && extrajson="$extrajson\n\"$URL\":{\n\t\"target\": \"$PROTOCOL$HOST:$PORT\",\n\t\"ws\": true\n\t},\n\t\"$URL\":{\n\t\"target\": \"$PROTOCOL$HOST:$PORT\"\n\t},"
  done < /tmp/.config
  if [[ -f $SELF_PATH/config.json ]]; then 
    { echo -e "{\n$extrajson"; tail -n+2 $SELF_PATH/config.json; } > $SELF_PATH/config.generated.json
  else end=$(( ${#extrajson}-1 )); echo -e "{ ${extrajson:0:end} } " > $SELF_PATH/config.generated.json; fi
}

startserver(){
  port=$1; 
  pid="$(netstat -nap | grep node | grep ":$port" | head -n1 | sed "s/.*LISTEN//g;s/\/.*//g;s/ //g")"; 
  [[ ${#pid} > 0 ]] && kill -9 $pid 
  cd $SELF_PATH 
  PORT=$port nohup ./proxy-server --table=config.generated.json &
  disown
}

generate_config 
startserver 80
